### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by logemann** [gmazelier/gradle-jasperreports#1]
Hi,

i tried to use your plugin but i got:

Error:Could not find com.lowagie:itext:2.1.7.js2.
Searched in the following locations:
    https://jcenter.bintray.com/com/lowagie/itext/2.1.7.js2/itext-2.1.7.js2.pom
    https://jcenter.bintray.com/com/lowagie/itext/2.1.7.js2/itext-2.1.7.js2.jar
Required by:
    :Netversys3:unspecified > com.github.gmazelier:jasperreports-gradle-plugin:0.1.0 > net.sf.jasperreports:jasperreports:5.2.0

in the jcenter repos there is no "2.1.7.js2" folder but only "2.1.7".

**Comment by gmazelier** [comment]
Hi,

You're right, the doc seems incomplete. The required dependency is available in the Jasersoft Maven repo. Can you try with the following repo in your Gradle script:

```
maven {
  url 'http://jasperreports.sourceforge.net/maven2'
}
```

Maybe this one is required too but you should test without it first:

```
maven {
  url 'http://repository.jboss.org/maven2/'
}
```

Let me know.

**Comment by gmazelier** [comment]
README is now up to date. Have you made a try?

**Comment by gmazelier** [comment]
README update seems enough to close this issue.

**Comment by edgardleal** [comment]
I hade the same problem because i was using the dependencies registration outside of the attribute **buildscript**.
Here is a simple functional using default values for configuration **build.gradle** as in the **README.md**:

```Gradle
buildscript {
  repositories {
    jcenter()
      maven {
        url 'http://jaspersoft.artifactoryonline.com/jaspersoft/third-party-ce-artifacts/'
      }
    maven {
      url 'http://jasperreports.sourceforge.net/maven2'
    }
    maven {
      url 'http://repository.jboss.org/maven2/'
    }
  }
  dependencies {
    classpath 'com.github.gmazelier:jasperreports-gradle-plugin:0.3.2'
  }
}

apply plugin: 'com.github.gmazelier.jasperreports'
```

**Comment by mpscheidt** [comment]
To use the plugin via its id, I had to provide the dependencies like this:

```
buildscript {
    repositories {
        maven {
            url 'http://jaspersoft.artifactoryonline.com/jaspersoft/third-party-ce-artifacts/'
        }
}

plugins {
    id 'com.github.gmazelier.jasperreports' version '0.3.2'
}

```
