### ISSUE TITLE
Documentation: tmpDir, outdir should use doubles quotes

### ISSUE THREAD

**Issue by mpscheidt** [gmazelier/gradle-jasperreports#10]
There is an error in the documentation: 
```
tmpDir = file('${project.buildDir}/jasperreports')
outDir = file('${project.buildDir}/classes/main')

```
This will create a directory called `${project.buildDir}` in the project's main dir.

Example should use double quotes to specify tmpDir and outDir, in order to support String interpolation, replacing `${project.buildDir}` with its value:
```
tmpDir = file("${project.buildDir}/jasperreports")
outDir = file("${project.buildDir}/classes/main")

```

**Comment by gmazelier** [comment]
Fixed by 3652cf773289652aa8fdd9b629ba1357e3c8e977.
