### ISSUE TITLE
Problem with dependency

### ISSUE THREAD

**Issue by ichromanrd** [gmazelier/gradle-jasperreports#13]
Hi @gmazelier 

This plugin is so cool. Are you still maintaining this? I have a problem with this plugin, got this error:

![image](https://user-images.githubusercontent.com/4666629/63940403-99273e80-ca93-11e9-88ba-109e5c978312.png)

Could this because the outdated dependencies or some broken repository urls?

**Comment by unib1t** [comment]
I got same problem. The only repo still serving this library version is 
http://maven.icm.edu.pl/artifactory/repo/
Add this repo in your buildscript repositories

**Comment by ichromanrd** [comment]
> I got same problem. The only repo still serving this library version is
> http://maven.icm.edu.pl/artifactory/repo/
> Add this repo in your buildscript repositories

Thank you for suggestion, but I have used another way 😃 

I think this project should be updated.

**Comment by tkofford** [comment]
This project does need updating. I don't mind doing the work and submitting a pull request, if people besides myself find it useful? The only part I don't have experience with is "releasing" the plugin and making it available to everyone.

**Comment by gmazelier** [comment]
Hi there. @tkofford, your contribution is welcome. Submit a pull request and if will release a new version.

**Comment by ghost** [comment]
We're having the same problem. A fix would be welcoming :)!

**Comment by tkofford** [comment]
Hi @gmazelier, pull request created. There is a little bit of work for you to do as the author though, so please read through the commit message and contact me if you have any questions or feedback.
