### ISSUE TITLE
classpath property not recognized

### ISSUE THREAD

**Issue by welkman** [gmazelier/gradle-jasperreports#3]
I tried the leaving untouched all of the default configuration property values, before I realized our classpath is not standard.  So I tried replacing it, but I get:

> No such property: classpath for class: com.github.gmazelier.plugins.JasperReportsExtension_Decorated

I even copy-pasted the default line on the project overview doc, and I get the same result.

**Comment by welkman** [comment]
I figured out that your documentation is ahead of your releases.  I guess "classpath" will be available in your next release, unless I want to get the SNAPSHOT and build it myself.

**Comment by gmazelier** [comment]
Indeed. I've just release `0.2.0` with the `classpath` property available and improved documentation.
